name: Playwright Tests

on:
  push:
    branches: [main, master]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t playwright-from-scratch .

      - name: Run Playwright Tests in Docker
        env:
          BASE_URL: "https://www.saucedemo.com/"
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: |
          docker run --rm -v $(pwd)/allure-results:/app/allure-results \
            -e BASE_URL=${BASE_URL} \
            -e USERNAME=${USERNAME} \
            -e PASSWORD=${PASSWORD} \
            playwright-from-scratch

      - name: Install Allure Commandline
        run: npm install -g allure-commandline

      - name: Generate Allure Report
        run: npx allure-commandline generate ./allure-results --clean -o ./allure-report

      - name: Upload Allure Report Artifact
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: ./allure-report
          retention-days: 30